/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VienaRouteImport } from './routes/viena'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RoteiroPersonalizadoRouteImport } from './routes/roteiro-personalizado'
import { Route as PragaRouteImport } from './routes/praga'
import { Route as ParisRouteImport } from './routes/paris'
import { Route as LondresRouteImport } from './routes/londres'
import { Route as LisboaRouteImport } from './routes/lisboa'
import { Route as IstambulRouteImport } from './routes/istambul'
import { Route as FlorencaRouteImport } from './routes/florenca'
import { Route as BudapesteRouteImport } from './routes/budapeste'
import { Route as BarcelonaRouteImport } from './routes/barcelona'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AbordagemRouteImport } from './routes/abordagem'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuiaSlugRouteImport } from './routes/guia.$slug'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedGuiasIndexRouteImport } from './routes/_authenticated/guias.index'
import { Route as AuthenticatedGuiasIdRouteImport } from './routes/_authenticated/guias.$id'
import { Route as ApiPublicGuideImageSplatRouteImport } from './routes/api/public/guide-image/$'

const VienaRoute = VienaRouteImport.update({
  id: '/viena',
  path: '/viena',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RoteiroPersonalizadoRoute = RoteiroPersonalizadoRouteImport.update({
  id: '/roteiro-personalizado',
  path: '/roteiro-personalizado',
  getParentRoute: () => rootRouteImport,
} as any)
const PragaRoute = PragaRouteImport.update({
  id: '/praga',
  path: '/praga',
  getParentRoute: () => rootRouteImport,
} as any)
const ParisRoute = ParisRouteImport.update({
  id: '/paris',
  path: '/paris',
  getParentRoute: () => rootRouteImport,
} as any)
const LondresRoute = LondresRouteImport.update({
  id: '/londres',
  path: '/londres',
  getParentRoute: () => rootRouteImport,
} as any)
const LisboaRoute = LisboaRouteImport.update({
  id: '/lisboa',
  path: '/lisboa',
  getParentRoute: () => rootRouteImport,
} as any)
const IstambulRoute = IstambulRouteImport.update({
  id: '/istambul',
  path: '/istambul',
  getParentRoute: () => rootRouteImport,
} as any)
const FlorencaRoute = FlorencaRouteImport.update({
  id: '/florenca',
  path: '/florenca',
  getParentRoute: () => rootRouteImport,
} as any)
const BudapesteRoute = BudapesteRouteImport.update({
  id: '/budapeste',
  path: '/budapeste',
  getParentRoute: () => rootRouteImport,
} as any)
const BarcelonaRoute = BarcelonaRouteImport.update({
  id: '/barcelona',
  path: '/barcelona',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AbordagemRoute = AbordagemRouteImport.update({
  id: '/abordagem',
  path: '/abordagem',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiaSlugRoute = GuiaSlugRouteImport.update({
  id: '/guia/$slug',
  path: '/guia/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGuiasIndexRoute = AuthenticatedGuiasIndexRouteImport.update({
  id: '/guias/',
  path: '/guias/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGuiasIdRoute = AuthenticatedGuiasIdRouteImport.update({
  id: '/guias/$id',
  path: '/guias/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicGuideImageSplatRoute =
  ApiPublicGuideImageSplatRouteImport.update({
    id: '/api/public/guide-image/$',
    path: '/api/public/guide-image/$',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/abordagem': typeof AbordagemRoute
  '/auth': typeof AuthRoute
  '/barcelona': typeof BarcelonaRoute
  '/budapeste': typeof BudapesteRoute
  '/florenca': typeof FlorencaRoute
  '/istambul': typeof IstambulRoute
  '/lisboa': typeof LisboaRoute
  '/londres': typeof LondresRoute
  '/paris': typeof ParisRoute
  '/praga': typeof PragaRoute
  '/roteiro-personalizado': typeof RoteiroPersonalizadoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/viena': typeof VienaRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/guia/$slug': typeof GuiaSlugRoute
  '/guias/$id': typeof AuthenticatedGuiasIdRoute
  '/guias/': typeof AuthenticatedGuiasIndexRoute
  '/api/public/guide-image/$': typeof ApiPublicGuideImageSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/abordagem': typeof AbordagemRoute
  '/auth': typeof AuthRoute
  '/barcelona': typeof BarcelonaRoute
  '/budapeste': typeof BudapesteRoute
  '/florenca': typeof FlorencaRoute
  '/istambul': typeof IstambulRoute
  '/lisboa': typeof LisboaRoute
  '/londres': typeof LondresRoute
  '/paris': typeof ParisRoute
  '/praga': typeof PragaRoute
  '/roteiro-personalizado': typeof RoteiroPersonalizadoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/viena': typeof VienaRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/guia/$slug': typeof GuiaSlugRoute
  '/guias/$id': typeof AuthenticatedGuiasIdRoute
  '/guias': typeof AuthenticatedGuiasIndexRoute
  '/api/public/guide-image/$': typeof ApiPublicGuideImageSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/abordagem': typeof AbordagemRoute
  '/auth': typeof AuthRoute
  '/barcelona': typeof BarcelonaRoute
  '/budapeste': typeof BudapesteRoute
  '/florenca': typeof FlorencaRoute
  '/istambul': typeof IstambulRoute
  '/lisboa': typeof LisboaRoute
  '/londres': typeof LondresRoute
  '/paris': typeof ParisRoute
  '/praga': typeof PragaRoute
  '/roteiro-personalizado': typeof RoteiroPersonalizadoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/viena': typeof VienaRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/guia/$slug': typeof GuiaSlugRoute
  '/_authenticated/guias/$id': typeof AuthenticatedGuiasIdRoute
  '/_authenticated/guias/': typeof AuthenticatedGuiasIndexRoute
  '/api/public/guide-image/$': typeof ApiPublicGuideImageSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/abordagem'
    | '/auth'
    | '/barcelona'
    | '/budapeste'
    | '/florenca'
    | '/istambul'
    | '/lisboa'
    | '/londres'
    | '/paris'
    | '/praga'
    | '/roteiro-personalizado'
    | '/sitemap.xml'
    | '/viena'
    | '/admin'
    | '/guia/$slug'
    | '/guias/$id'
    | '/guias/'
    | '/api/public/guide-image/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/abordagem'
    | '/auth'
    | '/barcelona'
    | '/budapeste'
    | '/florenca'
    | '/istambul'
    | '/lisboa'
    | '/londres'
    | '/paris'
    | '/praga'
    | '/roteiro-personalizado'
    | '/sitemap.xml'
    | '/viena'
    | '/admin'
    | '/guia/$slug'
    | '/guias/$id'
    | '/guias'
    | '/api/public/guide-image/$'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/abordagem'
    | '/auth'
    | '/barcelona'
    | '/budapeste'
    | '/florenca'
    | '/istambul'
    | '/lisboa'
    | '/londres'
    | '/paris'
    | '/praga'
    | '/roteiro-personalizado'
    | '/sitemap.xml'
    | '/viena'
    | '/_authenticated/admin'
    | '/guia/$slug'
    | '/_authenticated/guias/$id'
    | '/_authenticated/guias/'
    | '/api/public/guide-image/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AbordagemRoute: typeof AbordagemRoute
  AuthRoute: typeof AuthRoute
  BarcelonaRoute: typeof BarcelonaRoute
  BudapesteRoute: typeof BudapesteRoute
  FlorencaRoute: typeof FlorencaRoute
  IstambulRoute: typeof IstambulRoute
  LisboaRoute: typeof LisboaRoute
  LondresRoute: typeof LondresRoute
  ParisRoute: typeof ParisRoute
  PragaRoute: typeof PragaRoute
  RoteiroPersonalizadoRoute: typeof RoteiroPersonalizadoRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VienaRoute: typeof VienaRoute
  GuiaSlugRoute: typeof GuiaSlugRoute
  ApiPublicGuideImageSplatRoute: typeof ApiPublicGuideImageSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/viena': {
      id: '/viena'
      path: '/viena'
      fullPath: '/viena'
      preLoaderRoute: typeof VienaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roteiro-personalizado': {
      id: '/roteiro-personalizado'
      path: '/roteiro-personalizado'
      fullPath: '/roteiro-personalizado'
      preLoaderRoute: typeof RoteiroPersonalizadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/praga': {
      id: '/praga'
      path: '/praga'
      fullPath: '/praga'
      preLoaderRoute: typeof PragaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paris': {
      id: '/paris'
      path: '/paris'
      fullPath: '/paris'
      preLoaderRoute: typeof ParisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/londres': {
      id: '/londres'
      path: '/londres'
      fullPath: '/londres'
      preLoaderRoute: typeof LondresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lisboa': {
      id: '/lisboa'
      path: '/lisboa'
      fullPath: '/lisboa'
      preLoaderRoute: typeof LisboaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/istambul': {
      id: '/istambul'
      path: '/istambul'
      fullPath: '/istambul'
      preLoaderRoute: typeof IstambulRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/florenca': {
      id: '/florenca'
      path: '/florenca'
      fullPath: '/florenca'
      preLoaderRoute: typeof FlorencaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budapeste': {
      id: '/budapeste'
      path: '/budapeste'
      fullPath: '/budapeste'
      preLoaderRoute: typeof BudapesteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/barcelona': {
      id: '/barcelona'
      path: '/barcelona'
      fullPath: '/barcelona'
      preLoaderRoute: typeof BarcelonaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abordagem': {
      id: '/abordagem'
      path: '/abordagem'
      fullPath: '/abordagem'
      preLoaderRoute: typeof AbordagemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guia/$slug': {
      id: '/guia/$slug'
      path: '/guia/$slug'
      fullPath: '/guia/$slug'
      preLoaderRoute: typeof GuiaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/guias/': {
      id: '/_authenticated/guias/'
      path: '/guias'
      fullPath: '/guias/'
      preLoaderRoute: typeof AuthenticatedGuiasIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/guias/$id': {
      id: '/_authenticated/guias/$id'
      path: '/guias/$id'
      fullPath: '/guias/$id'
      preLoaderRoute: typeof AuthenticatedGuiasIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/guide-image/$': {
      id: '/api/public/guide-image/$'
      path: '/api/public/guide-image/$'
      fullPath: '/api/public/guide-image/$'
      preLoaderRoute: typeof ApiPublicGuideImageSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedGuiasIdRoute: typeof AuthenticatedGuiasIdRoute
  AuthenticatedGuiasIndexRoute: typeof AuthenticatedGuiasIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedGuiasIdRoute: AuthenticatedGuiasIdRoute,
  AuthenticatedGuiasIndexRoute: AuthenticatedGuiasIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AbordagemRoute: AbordagemRoute,
  AuthRoute: AuthRoute,
  BarcelonaRoute: BarcelonaRoute,
  BudapesteRoute: BudapesteRoute,
  FlorencaRoute: FlorencaRoute,
  IstambulRoute: IstambulRoute,
  LisboaRoute: LisboaRoute,
  LondresRoute: LondresRoute,
  ParisRoute: ParisRoute,
  PragaRoute: PragaRoute,
  RoteiroPersonalizadoRoute: RoteiroPersonalizadoRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VienaRoute: VienaRoute,
  GuiaSlugRoute: GuiaSlugRoute,
  ApiPublicGuideImageSplatRoute: ApiPublicGuideImageSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
