/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PragaRouteImport } from './routes/praga'
import { Route as IndexRouteImport } from './routes/index'

const PragaRoute = PragaRouteImport.update({
  id: '/praga',
  path: '/praga',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/praga': typeof PragaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/praga': typeof PragaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/praga': typeof PragaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/praga'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/praga'
  id: '__root__' | '/' | '/praga'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PragaRoute: typeof PragaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/praga': {
      id: '/praga'
      path: '/praga'
      fullPath: '/praga'
      preLoaderRoute: typeof PragaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PragaRoute: PragaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
